using SimpleEFDbSeeder.Entities;

namespace SimpleEFDbSeeder
{
    public static class SampleData
    {
        

        public static List<Country> Countries => new()
        {
            new Country() { CountryName = "Afghanistan", Alpha2 = "AF", Alpha3 = "AFG", NumericCode = "004", Es="Afganistán", En="Afghanistan" },
            new Country() { CountryName = "Albania", Alpha2 = "AL", Alpha3 = "ALB", NumericCode = "008", Es="Albania", En="Albania" },
            new Country() { CountryName = "Algeria", Alpha2 = "DZ", Alpha3 = "DZA", NumericCode = "012", Es="Argelia", En="Algeria" },
            new Country() { CountryName = "American Samoa", Alpha2 = "AS", Alpha3 = "ASM", NumericCode = "016", Es="Samoa Americana", En="American Samoa" },
            new Country() { CountryName = "Andorra", Alpha2 = "AD", Alpha3 = "AND", NumericCode = "020", Es="Andorra", En="Andorra" },
            new Country() { CountryName = "Angola", Alpha2 = "AO", Alpha3 = "AGO", NumericCode = "024", Es="Angola", En="Angola" },
            new Country() { CountryName = "Anguilla", Alpha2 = "AI", Alpha3 = "AIA", NumericCode = "660", Es="Anguila", En="Anguilla" },
            new Country() { CountryName = "Antarctica", Alpha2 = "AQ", Alpha3 = "ATA", NumericCode = "010", Es="Antártida", En="Antarctica" },
            new Country() { CountryName = "Antigua and Barbuda", Alpha2 = "AG", Alpha3 = "ATG", NumericCode = "028", Es="Antigua y Barbuda", En="Antigua and Barbuda" },
            new Country() { CountryName = "Argentina", Alpha2 = "AR", Alpha3 = "ARG", NumericCode = "032", Es="Argentina", En="Argentina" },
            new Country() { CountryName = "Armenia", Alpha2 = "AM", Alpha3 = "ARM", NumericCode = "051", Es="Armenia", En="Armenia" },
            new Country() { CountryName = "Aruba", Alpha2 = "AW", Alpha3 = "ABW", NumericCode = "533", Es="Aruba", En="Aruba" },
            new Country() { CountryName = "Australia", Alpha2 = "AU", Alpha3 = "AUS", NumericCode = "036", Es="Australia", En="Australia" },
            new Country() { CountryName = "Austria", Alpha2 = "AT", Alpha3 = "AUT", NumericCode = "040", Es="Austria", En="Austria" },
            new Country() { CountryName = "Azerbaijan", Alpha2 = "AZ", Alpha3 = "AZE", NumericCode = "031", Es="Azerbaiyán", En="Azerbaijan" },
            new Country() { CountryName = "Bahamas", Alpha2 = "BS", Alpha3 = "BHS", NumericCode = "044", Es="Bahamas", En="Bahamas" },
            new Country() { CountryName = "Bahrain", Alpha2 = "BH", Alpha3 = "BHR", NumericCode = "048", Es="Baréin", En="Bahrain" },
            new Country() { CountryName = "Bangladesh", Alpha2 = "BD", Alpha3 = "BGD", NumericCode = "050", Es="Bangladés", En="Bangladesh" },
            new Country() { CountryName = "Barbados", Alpha2 = "BB", Alpha3 = "BRB", NumericCode = "052", Es="Barbados", En="Barbados" },
            new Country() { CountryName = "Belarus", Alpha2 = "BY", Alpha3 = "BLR", NumericCode = "112", Es="Bielorrusia", En="Belarus" },
            new Country() { CountryName = "Belgium", Alpha2 = "BE", Alpha3 = "BEL", NumericCode = "056", Es="Bélgica", En="Belgium" },
            new Country() { CountryName = "Belize", Alpha2 = "BZ", Alpha3 = "BLZ", NumericCode = "084", Es="Belice", En="Belize" },
            new Country() { CountryName = "Benin", Alpha2 = "BJ", Alpha3 = "BEN", NumericCode = "204", Es="Benín", En="Benin" },
            new Country() { CountryName = "Bhutan", Alpha2 = "BT", Alpha3 = "BTN", NumericCode = "064", Es="Bután", En="Bhutan" },
            new Country() { CountryName = "Bolivia", Alpha2 = "BO", Alpha3 = "BOL", NumericCode = "068", Es="Bolivia", En="Bolivia" },
            new Country() { CountryName = "Bosnia and Herzegovina", Alpha2 = "BA", Alpha3 = "BIH", NumericCode = "070", Es="Bosnia y Herzegovina", En="Bosnia and Herzegovina" },
            new Country() { CountryName = "Botswana", Alpha2 = "BW", Alpha3 = "BWA", NumericCode = "072", Es="Botsuana", En="Botswana" },
            new Country() { CountryName = "Brazil", Alpha2 = "BR", Alpha3 = "BRA", NumericCode = "076", Es="Brasil", En="Brazil" },
            new Country() { CountryName = "Brunei", Alpha2 = "BN", Alpha3 = "BRN", NumericCode = "096", Es="Brunéi", En="Brunei" },
            new Country() { CountryName = "Bulgaria", Alpha2 = "BG", Alpha3 = "BGR", NumericCode = "100", Es="Bulgaria", En="Bulgaria" },
            new Country() { CountryName = "Burkina Faso", Alpha2 = "BF", Alpha3 = "BFA", NumericCode = "854", Es="Burkina Faso", En="Burkina Faso" },
            new Country() { CountryName = "Burundi", Alpha2 = "BI", Alpha3 = "BDI", NumericCode = "108", Es="Burundi", En="Burundi" },
            new Country() { CountryName = "Cabo Verde", Alpha2 = "CV", Alpha3 = "CPV", NumericCode = "132", Es="Cabo Verde", En="Cabo Verde" },
            new Country() { CountryName = "Cambodia", Alpha2 = "KH", Alpha3 = "KHM", NumericCode = "116", Es="Camboya", En="Cambodia" },
            new Country() { CountryName = "Cameroon", Alpha2 = "CM", Alpha3 = "CMR", NumericCode = "120", Es="Camerún", En="Cameroon" },
            new Country() { CountryName = "Canada", Alpha2 = "CA", Alpha3 = "CAN", NumericCode = "124", Es="Canadá", En="Canada" },
            new Country() { CountryName = "Central African Republic", Alpha2 = "CF", Alpha3 = "CAF", NumericCode = "140", Es="República Centroafricana", En="Central African Republic" },
            new Country() { CountryName = "Chad", Alpha2 = "TD", Alpha3 = "TCD", NumericCode = "148", Es="Chad", En="Chad" },
            new Country() { CountryName = "Chile", Alpha2 = "CL", Alpha3 = "CHL", NumericCode = "152", Es="Chile", En="Chile" },
            new Country() { CountryName = "China", Alpha2 = "CN", Alpha3 = "CHN", NumericCode = "156", Es="China", En="China" },
            new Country() { CountryName = "Colombia", Alpha2 = "CO", Alpha3 = "COL", NumericCode = "170", Es="Colombia", En="Colombia" },
            new Country() { CountryName = "Comoros", Alpha2 = "KM", Alpha3 = "COM", NumericCode = "174", Es="Comoras", En="Comoros" },
            new Country() { CountryName = "Congo (Congo-Brazzaville)", Alpha2 = "CG", Alpha3 = "COG", NumericCode = "178", Es="Congo (Congo-Brazzaville)", En="Congo (Congo-Brazzaville)" },
            new Country() { CountryName = "Costa Rica", Alpha2 = "CR", Alpha3 = "CRI", NumericCode = "188", Es="Costa Rica", En="Costa Rica" },
            new Country() { CountryName = "Côte d'Ivoire", Alpha2 = "CI", Alpha3 = "CIV", NumericCode = "384", Es="Costa de Marfil", En="Côte d'Ivoire" },
            new Country() { CountryName = "Croatia", Alpha2 = "HR", Alpha3 = "HRV", NumericCode = "191", Es="Croacia", En="Croatia" },
            new Country() { CountryName = "Cuba", Alpha2 = "CU", Alpha3 = "CUB", NumericCode = "192", Es="Cuba", En="Cuba" },
            new Country() { CountryName = "Cyprus", Alpha2 = "CY", Alpha3 = "CYP", NumericCode = "196", Es="Chipre", En="Cyprus" },
            new Country() { CountryName = "Czechia", Alpha2 = "CZ", Alpha3 = "CZE", NumericCode = "203", Es="Chequia", En="Czechia" },
            new Country() { CountryName = "Democratic Republic of the Congo", Alpha2 = "CD", Alpha3 = "COD", NumericCode = "180", Es="República Democrática del Congo", En="Democratic Republic of the Congo" },
            new Country() { CountryName = "Denmark", Alpha2 = "DK", Alpha3 = "DNK", NumericCode = "208", Es="Dinamarca", En="Denmark" },
            new Country() { CountryName = "Djibouti", Alpha2 = "DJ", Alpha3 = "DJI", NumericCode = "262", Es="Yibuti", En="Djibouti" },
            new Country() { CountryName = "Dominica", Alpha2 = "DM", Alpha3 = "DMA", NumericCode = "212", Es="Dominica", En="Dominica" },
            new Country() { CountryName = "Dominican Republic", Alpha2 = "DO", Alpha3 = "DOM", NumericCode = "214", Es="República Dominicana", En="Dominican Republic" },
            new Country() { CountryName = "Ecuador", Alpha2 = "EC", Alpha3 = "ECU", NumericCode = "218", Es="Ecuador", En="Ecuador" },
            new Country() { CountryName = "Egypt", Alpha2 = "EG", Alpha3 = "EGY", NumericCode = "818", Es="Egipto", En="Egypt" },
            new Country() { CountryName = "El Salvador", Alpha2 = "SV", Alpha3 = "SLV", NumericCode = "222", Es="El Salvador", En="El Salvador" },
            new Country() { CountryName = "Equatorial Guinea", Alpha2 = "GQ", Alpha3 = "GNQ", NumericCode = "226", Es="Guinea Ecuatorial", En="Equatorial Guinea" },
            new Country() { CountryName = "Eritrea", Alpha2 = "ER", Alpha3 = "ERI", NumericCode = "232", Es="Eritrea", En="Eritrea" },
            new Country() { CountryName = "Estonia", Alpha2 = "EE", Alpha3 = "EST", NumericCode = "233", Es="Estonia", En="Estonia" },
            new Country() { CountryName = "Eswatini", Alpha2 = "SZ", Alpha3 = "SWZ", NumericCode = "748", Es="Esuatini", En="Eswatini" },
            new Country() { CountryName = "Ethiopia", Alpha2 = "ET", Alpha3 = "ETH", NumericCode = "231", Es="Etiopía", En="Ethiopia" },
            new Country() { CountryName = "Fiji", Alpha2 = "FJ", Alpha3 = "FJI", NumericCode = "242", Es="Fiyi", En="Fiji" },
            new Country() { CountryName = "Finland", Alpha2 = "FI", Alpha3 = "FIN", NumericCode = "246", Es="Finlandia", En="Finland" },
            new Country() { CountryName = "France", Alpha2 = "FR", Alpha3 = "FRA", NumericCode = "250", Es="Francia", En="France" },
            new Country() { CountryName = "Gabon", Alpha2 = "GA", Alpha3 = "GAB", NumericCode = "266", Es="Gabón", En="Gabon" },
            new Country() { CountryName = "Gambia", Alpha2 = "GM", Alpha3 = "GMB", NumericCode = "270", Es="Gambia", En="Gambia" },
            new Country() { CountryName = "Georgia", Alpha2 = "GE", Alpha3 = "GEO", NumericCode = "268", Es="Georgia", En="Georgia" },
            new Country() { CountryName = "Germany", Alpha2 = "DE", Alpha3 = "DEU", NumericCode = "276", Es="Alemania", En="Germany" },
            new Country() { CountryName = "Ghana", Alpha2 = "GH", Alpha3 = "GHA", NumericCode = "288", Es="Ghana", En="Ghana" },
            new Country() { CountryName = "Greece", Alpha2 = "GR", Alpha3 = "GRC", NumericCode = "300", Es="Grecia", En="Greece" },
            new Country() { CountryName = "Grenada", Alpha2 = "GD", Alpha3 = "GRD", NumericCode = "308", Es="Granada", En="Grenada" },
            new Country() { CountryName = "Guatemala", Alpha2 = "GT", Alpha3 = "GTM", NumericCode = "320", Es="Guatemala", En="Guatemala" },
            new Country() { CountryName = "Guinea", Alpha2 = "GN", Alpha3 = "GIN", NumericCode = "324", Es="Guinea", En="Guinea" },
            new Country() { CountryName = "Guinea-Bissau", Alpha2 = "GW", Alpha3 = "GNB", NumericCode = "624", Es="Guinea-Bisáu", En="Guinea-Bissau" },
            new Country() { CountryName = "Guyana", Alpha2 = "GY", Alpha3 = "GUY", NumericCode = "328", Es="Guyana", En="Guyana" },
            new Country() { CountryName = "Haiti", Alpha2 = "HT", Alpha3 = "HTI", NumericCode = "332", Es="Haití", En="Haiti" },
            new Country() { CountryName = "Honduras", Alpha2 = "HN", Alpha3 = "HND", NumericCode = "340", Es="Honduras", En="Honduras" },
            new Country() { CountryName = "Hungary", Alpha2 = "HU", Alpha3 = "HUN", NumericCode = "348", Es="Hungría", En="Hungary" },
            new Country() { CountryName = "Iceland", Alpha2 = "IS", Alpha3 = "ISL", NumericCode = "352", Es="Islandia", En="Iceland" },
            new Country() { CountryName = "India", Alpha2 = "IN", Alpha3 = "IND", NumericCode = "356", Es="India", En="India" },
            new Country() { CountryName = "Indonesia", Alpha2 = "ID", Alpha3 = "IDN", NumericCode = "360", Es="Indonesia", En="Indonesia" },
            new Country() { CountryName = "Iran", Alpha2 = "IR", Alpha3 = "IRN", NumericCode = "364", Es="Irán", En="Iran" },
            new Country() { CountryName = "Iraq", Alpha2 = "IQ", Alpha3 = "IRQ", NumericCode = "368", Es="Irak", En="Iraq" },
            new Country() { CountryName = "Ireland", Alpha2 = "IE", Alpha3 = "IRL", NumericCode = "372", Es="Irlanda", En="Ireland" },
            new Country() { CountryName = "Israel", Alpha2 = "IL", Alpha3 = "ISR", NumericCode = "376", Es="Israel", En="Israel" },
            new Country() { CountryName = "Italy", Alpha2 = "IT", Alpha3 = "ITA", NumericCode = "380", Es="Italia", En="Italy" },
            new Country() { CountryName = "Jamaica", Alpha2 = "JM", Alpha3 = "JAM", NumericCode = "388", Es="Jamaica", En="Jamaica" },
            new Country() { CountryName = "Japan", Alpha2 = "JP", Alpha3 = "JPN", NumericCode = "392", Es="Japón", En="Japan" },
            new Country() { CountryName = "Jordan", Alpha2 = "JO", Alpha3 = "JOR", NumericCode = "400", Es="Jordania", En="Jordan" },
            new Country() { CountryName = "Kazakhstan", Alpha2 = "KZ", Alpha3 = "KAZ", NumericCode = "398", Es="Kazajistán", En="Kazakhstan" },
            new Country() { CountryName = "Kenya", Alpha2 = "KE", Alpha3 = "KEN", NumericCode = "404", Es="Kenia", En="Kenya" },
            new Country() { CountryName = "Kiribati", Alpha2 = "KI", Alpha3 = "KIR", NumericCode = "296", Es="Kiribati", En="Kiribati" },
            new Country() { CountryName = "Korea, Democratic People's Republic of", Alpha2 = "KP", Alpha3 = "PRK", NumericCode = "408", Es="Corea del Norte", En="North Korea" },
            new Country() { CountryName = "Korea, Republic of", Alpha2 = "KR", Alpha3 = "KOR", NumericCode = "410", Es="Corea del Sur", En="South Korea" },
            new Country() { CountryName = "Kuwait", Alpha2 = "KW", Alpha3 = "KWT", NumericCode = "414", Es="Kuwait", En="Kuwait" },
            new Country() { CountryName = "Kyrgyzstan", Alpha2 = "KG", Alpha3 = "KGZ", NumericCode = "417", Es="Kirguistán", En="Kyrgyzstan" },
            new Country() { CountryName = "Lao People's Democratic Republic", Alpha2 = "LA", Alpha3 = "LAO", NumericCode = "418", Es="Laos", En="Laos" },
            new Country() { CountryName = "Latvia", Alpha2 = "LV", Alpha3 = "LVA", NumericCode = "428", Es="Letonia", En="Latvia" },
            new Country() { CountryName = "Lebanon", Alpha2 = "LB", Alpha3 = "LBN", NumericCode = "422", Es="Líbano", En="Lebanon" },
            new Country() { CountryName = "Lesotho", Alpha2 = "LS", Alpha3 = "LSO", NumericCode = "426", Es="Lesoto", En="Lesotho" },
            new Country() { CountryName = "Liberia", Alpha2 = "LR", Alpha3 = "LBR", NumericCode = "430", Es="Liberia", En="Liberia" },
            new Country() { CountryName = "Libya", Alpha2 = "LY", Alpha3 = "LBY", NumericCode = "434", Es="Libia", En="Libya" },
            new Country() { CountryName = "Liechtenstein", Alpha2 = "LI", Alpha3 = "LIE", NumericCode = "438", Es="Liechtenstein", En="Liechtenstein" },
            new Country() { CountryName = "Lithuania", Alpha2 = "LT", Alpha3 = "LTU", NumericCode = "440", Es="Lituania", En="Lithuania" },
            new Country() { CountryName = "Luxembourg", Alpha2 = "LU", Alpha3 = "LUX", NumericCode = "442", Es="Luxemburgo", En="Luxembourg" },
            new Country() { CountryName = "Macao", Alpha2 = "MO", Alpha3 = "MAC", NumericCode = "446", Es="Macao", En="Macao" },
            new Country() { CountryName = "Macedonia", Alpha2 = "MK", Alpha3 = "MKD", NumericCode = "807", Es="Macedonia", En="Macedonia" },
            new Country() { CountryName = "Madagascar", Alpha2 = "MG", Alpha3 = "MDG", NumericCode = "450", Es="Madagascar", En="Madagascar" },
            new Country() { CountryName = "Malawi", Alpha2 = "MW", Alpha3 = "MWI", NumericCode = "454", Es="Malawi", En="Malawi" },
            new Country() { CountryName = "Malaysia", Alpha2 = "MY", Alpha3 = "MYS", NumericCode = "458", Es="Malasia", En="Malaysia" },
            new Country() { CountryName = "Maldives", Alpha2 = "MV", Alpha3 = "MDV", NumericCode = "462", Es="Maldivas", En="Maldives" },
            new Country() { CountryName = "Mali", Alpha2 = "ML", Alpha3 = "MLI", NumericCode = "466", Es="Mali", En="Mali" },
            new Country() { CountryName = "Malta", Alpha2 = "MT", Alpha3 = "MLT", NumericCode = "470", Es="Malta", En="Malta" },
            new Country() { CountryName = "Marshall Islands", Alpha2 = "MH", Alpha3 = "MHL", NumericCode = "584", Es="Islas Marshall", En="Marshall Islands" },
            new Country() { CountryName = "Martinique", Alpha2 = "MQ", Alpha3 = "MTQ", NumericCode = "474", Es="Martinica", En="Martinique" },
            new Country() { CountryName = "Mauritania", Alpha2 = "MR", Alpha3 = "MRT", NumericCode = "478", Es="Mauritania", En="Mauritania" },
            new Country() { CountryName = "Mauritius", Alpha2 = "MU", Alpha3 = "MUS", NumericCode = "480", Es="Mauricio", En="Mauritius" },
            new Country() { CountryName = "Mayotte", Alpha2 = "YT", Alpha3 = "MYT", NumericCode = "175", Es="Mayotte", En="Mayotte" },
            new Country() { CountryName = "Mexico", Alpha2 = "MX", Alpha3 = "MEX", NumericCode = "484", Es="México", En="Mexico" },
            new Country() { CountryName = "Micronesia, Federated States of", Alpha2 = "FM", Alpha3 = "FSM", NumericCode = "583", Es="Micronesia", En="Micronesia" },
            new Country() { CountryName = "Moldova, Republic of", Alpha2 = "MD", Alpha3 = "MDA", NumericCode = "498", Es="Moldavia", En="Moldova" },
            new Country() { CountryName = "Monaco", Alpha2 = "MC", Alpha3 = "MCO", NumericCode = "492", Es="Mónaco", En="Monaco" },
            new Country() { CountryName = "Mongolia", Alpha2 = "MN", Alpha3 = "MNG", NumericCode = "496", Es="Mongolia", En="Mongolia" },
            new Country() { CountryName = "Montenegro", Alpha2 = "ME", Alpha3 = "MNE", NumericCode = "499", Es="Montenegro", En="Montenegro" },
            new Country() { CountryName = "Montserrat", Alpha2 = "MS", Alpha3 = "MSR", NumericCode = "500", Es="Montserrat", En="Montserrat" },
            new Country() { CountryName = "Morocco", Alpha2 = "MA", Alpha3 = "MAR", NumericCode = "504", Es="Marruecos", En="Morocco" },
            new Country() { CountryName = "Mozambique", Alpha2 = "MZ", Alpha3 = "MOZ", NumericCode = "508", Es="Mozambique", En="Mozambique" },
            new Country() { CountryName = "Myanmar", Alpha2 = "MM", Alpha3 = "MMR", NumericCode = "104", Es="Myanmar", En="Myanmar" },
            new Country() { CountryName = "Namibia", Alpha2 = "NA", Alpha3 = "NAM", NumericCode = "516", Es="Namibia", En="Namibia" },
            new Country() { CountryName = "Nauru", Alpha2 = "NR", Alpha3 = "NRU", NumericCode = "520", Es="Nauru", En="Nauru" },
            new Country() { CountryName = "Nepal", Alpha2 = "NP", Alpha3 = "NPL", NumericCode = "524", Es="Nepal", En="Nepal" },
            new Country() { CountryName = "Netherlands", Alpha2 = "NL", Alpha3 = "NLD", NumericCode = "528", Es="Países Bajos", En="Netherlands" },
            new Country() { CountryName = "New Caledonia", Alpha2 = "NC", Alpha3 = "NCL", NumericCode = "540", Es="Nueva Caledonia", En="New Caledonia" },
            new Country() { CountryName = "New Zealand", Alpha2 = "NZ", Alpha3 = "NZL", NumericCode = "554", Es="Nueva Zelanda", En="New Zealand" },
            new Country() { CountryName = "Nicaragua", Alpha2 = "NI", Alpha3 = "NIC", NumericCode = "558", Es="Nicaragua", En="Nicaragua" },
            new Country() { CountryName = "Niger", Alpha2 = "NE", Alpha3 = "NER", NumericCode = "562", Es="Níger", En="Niger" },
            new Country() { CountryName = "Nigeria", Alpha2 = "NG", Alpha3 = "NGA", NumericCode = "566", Es="Nigeria", En="Nigeria" },
            new Country() { CountryName = "Niue", Alpha2 = "NU", Alpha3 = "NIU", NumericCode = "570", Es="Niue", En="Niue" },
            new Country() { CountryName = "Norfolk Island", Alpha2 = "NF", Alpha3 = "NFK", NumericCode = "574", Es="Isla Norfolk", En="Norfolk Island" },
            new Country() { CountryName = "North Macedonia", Alpha2 = "MK", Alpha3 = "MKD", NumericCode = "807", Es="Macedonia del Norte", En="North Macedonia" },
            new Country() { CountryName = "Northern Mariana Islands", Alpha2 = "MP", Alpha3 = "MNP", NumericCode = "580", Es="Islas Marianas del Norte", En="Northern Mariana Islands" },
            new Country() { CountryName = "Norway", Alpha2 = "NO", Alpha3 = "NOR", NumericCode = "578", Es="Noruega", En="Norway" },
            new Country() { CountryName = "Oman", Alpha2 = "OM", Alpha3 = "OMN", NumericCode = "512", Es="Omán", En="Oman" },
            new Country() { CountryName = "Pakistan", Alpha2 = "PK", Alpha3 = "PAK", NumericCode = "586", Es="Pakistán", En="Pakistan" },
            new Country() { CountryName = "Palau", Alpha2 = "PW", Alpha3 = "PLW", NumericCode = "585", Es="Palaos", En="Palau" },
            new Country() { CountryName = "Palestine, State of", Alpha2 = "PS", Alpha3 = "PSE", NumericCode = "275", Es="Palestina", En="Palestine" },
            new Country() { CountryName = "Panama", Alpha2 = "PA", Alpha3 = "PAN", NumericCode = "591", Es="Panamá", En="Panama" },
            new Country() { CountryName = "Papua New Guinea", Alpha2 = "PG", Alpha3 = "PNG", NumericCode = "598", Es="Papúa Nueva Guinea", En="Papua New Guinea" },
            new Country() { CountryName = "Paraguay", Alpha2 = "PY", Alpha3 = "PRY", NumericCode = "600", Es="Paraguay", En="Paraguay" },
            new Country() { CountryName = "Peru", Alpha2 = "PE", Alpha3 = "PER", NumericCode = "604", Es="Perú", En="Peru" },
            new Country() { CountryName = "Philippines", Alpha2 = "PH", Alpha3 = "PHL", NumericCode = "608", Es="Filipinas", En="Philippines" },
            new Country() { CountryName = "Pitcairn", Alpha2 = "PN", Alpha3 = "PCN", NumericCode = "612", Es="Islas Pitcairn", En="Pitcairn" },
            new Country() { CountryName = "Poland", Alpha2 = "PL", Alpha3 = "POL", NumericCode = "616", Es="Polonia", En="Poland" },
            new Country() { CountryName = "Portugal", Alpha2 = "PT", Alpha3 = "PRT", NumericCode = "620", Es="Portugal", En="Portugal" },
            new Country() { CountryName = "Puerto Rico", Alpha2 = "PR", Alpha3 = "PRI", NumericCode = "630", Es="Puerto Rico", En="Puerto Rico" },
            new Country() { CountryName = "Qatar", Alpha2 = "QA", Alpha3 = "QAT", NumericCode = "634", Es="Catar", En="Qatar" },
            new Country() { CountryName = "Réunion", Alpha2 = "RE", Alpha3 = "REU", NumericCode = "638", Es="Reunión", En="Réunion" },
            new Country() { CountryName = "Romania", Alpha2 = "RO", Alpha3 = "ROU", NumericCode = "642", Es="Rumania", En="Romania" },
            new Country() { CountryName = "Russian Federation", Alpha2 = "RU", Alpha3 = "RUS", NumericCode = "643", Es="Rusia", En="Russia" },
            new Country() { CountryName = "Rwanda", Alpha2 = "RW", Alpha3 = "RWA", NumericCode = "646", Es="Ruanda", En="Rwanda" },
            new Country() { CountryName = "Saint Barthélemy", Alpha2 = "BL", Alpha3 = "BLM", NumericCode = "652", Es="San Bartolomé", En="Saint Barthélemy" },
            new Country() { CountryName = "Saint Helena, Ascension and Tristan da Cunha", Alpha2 = "SH", Alpha3 = "SHN", NumericCode = "654", Es="Santa Elena, Ascensión y Tristán de Acuña", En="Saint Helena, Ascension and Tristan da Cunha" },
            new Country() { CountryName = "Saint Kitts and Nevis", Alpha2 = "KN", Alpha3 = "KNA", NumericCode = "659", Es="San Cristóbal y Nieves", En="Saint Kitts and Nevis" },
            new Country() { CountryName = "Saint Lucia", Alpha2 = "LC", Alpha3 = "LCA", NumericCode = "662", Es="Santa Lucía", En="Saint Lucia" },
            new Country() { CountryName = "Saint Martin (French part)", Alpha2 = "MF", Alpha3 = "MAF", NumericCode = "663", Es="San Martín (parte francesa)", En="Saint Martin (French part)" },
            new Country() { CountryName = "Saint Pierre and Miquelon", Alpha2 = "PM", Alpha3 = "SPM", NumericCode = "666", Es="San Pedro y Miquelón", En="Saint Pierre and Miquelon" },
            new Country() { CountryName = "Saint Vincent and the Grenadines", Alpha2 = "VC", Alpha3 = "VCT", NumericCode = "670", Es="San Vicente y las Granadinas", En="Saint Vincent and the Grenadines" },
            new Country() { CountryName = "Samoa", Alpha2 = "WS", Alpha3 = "WSM", NumericCode = "882", Es="Samoa", En="Samoa" },
            new Country() { CountryName = "San Marino", Alpha2 = "SM", Alpha3 = "SMR", NumericCode = "674", Es="San Marino", En="San Marino" },
            new Country() { CountryName = "Sao Tome and Principe", Alpha2 = "ST", Alpha3 = "STP", NumericCode = "678", Es="Santo Tomé y Príncipe", En="Sao Tome and Principe" },
            new Country() { CountryName = "Saudi Arabia", Alpha2 = "SA", Alpha3 = "SAU", NumericCode = "682", Es="Arabia Saudita", En="Saudi Arabia" },
            new Country() { CountryName = "Senegal", Alpha2 = "SN", Alpha3 = "SEN", NumericCode = "686", Es="Senegal", En="Senegal" },
            new Country() { CountryName = "Serbia", Alpha2 = "RS", Alpha3 = "SRB", NumericCode = "688", Es="Serbia", En="Serbia" },
            new Country() { CountryName = "Seychelles", Alpha2 = "SC", Alpha3 = "SYC", NumericCode = "690", Es="Seychelles", En="Seychelles" },
            new Country() { CountryName = "Sierra Leone", Alpha2 = "SL", Alpha3 = "SLE", NumericCode = "694", Es="Sierra Leona", En="Sierra Leone" },
            new Country() { CountryName = "Singapore", Alpha2 = "SG", Alpha3 = "SGP", NumericCode = "702", Es="Singapur", En="Singapore" },
            new Country() { CountryName = "Sint Maarten (Dutch part)", Alpha2 = "SX", Alpha3 = "SXM", NumericCode = "534", Es="San Martín (parte holandesa)", En="Sint Maarten (Dutch part)" },
            new Country() { CountryName = "Slovakia", Alpha2 = "SK", Alpha3 = "SVK", NumericCode = "703", Es="Eslovaquia", En="Slovakia" },
            new Country() { CountryName = "Slovenia", Alpha2 = "SI", Alpha3 = "SVN", NumericCode = "705", Es="Eslovenia", En="Slovenia" },
            new Country() { CountryName = "Solomon Islands", Alpha2 = "SB", Alpha3 = "SLB", NumericCode = "090", Es="Islas Salomón", En="Solomon Islands" },
            new Country() { CountryName = "Somalia", Alpha2 = "SO", Alpha3 = "SOM", NumericCode = "706", Es="Somalia", En="Somalia" },
            new Country() { CountryName = "South Africa", Alpha2 = "ZA", Alpha3 = "ZAF", NumericCode = "710", Es="Sudáfrica", En="South Africa" },
            new Country() { CountryName = "South Georgia and the South Sandwich Islands", Alpha2 = "GS", Alpha3 = "SGS", NumericCode = "239", Es="Islas Georgias del Sur y Sandwich del Sur", En="South Georgia and the South Sandwich Islands" },
            new Country() { CountryName = "South Sudan", Alpha2 = "SS", Alpha3 = "SSD", NumericCode = "728", Es="Sudán del Sur", En="South Sudan" },
            new Country() { CountryName = "Spain", Alpha2 = "ES", Alpha3 = "ESP", NumericCode = "724", Es="España", En="Spain" },
            new Country() { CountryName = "Sri Lanka", Alpha2 = "LK", Alpha3 = "LKA", NumericCode = "144", Es="Sri Lanka", En="Sri Lanka" },
            new Country() { CountryName = "Sudan", Alpha2 = "SD", Alpha3 = "SDN", NumericCode = "729", Es="Sudán", En="Sudan" },
            new Country() { CountryName = "Suriname", Alpha2 = "SR", Alpha3 = "SUR", NumericCode = "740", Es="Surinam", En="Suriname" },
            new Country() { CountryName = "Svalbard og Jan Mayen", Alpha2 = "SJ", Alpha3 = "SJM", NumericCode = "744", Es="Svalbard y Jan Mayen", En="Svalbard and Jan Mayen" },
            new Country() { CountryName = "Eswatini", Alpha2 = "SZ", Alpha3 = "SWZ", NumericCode = "748", Es="Suazilandia", En="Eswatini" },
            new Country() { CountryName = "Sweden", Alpha2 = "SE", Alpha3 = "SWE", NumericCode = "752", Es="Suecia", En="Sweden" },
            new Country() { CountryName = "Switzerland", Alpha2 = "CH", Alpha3 = "CHE", NumericCode = "756", Es="Suiza", En="Switzerland" },
            new Country() { CountryName = "Syrian Arab Republic", Alpha2 = "SY", Alpha3 = "SYR", NumericCode = "760", Es="República Árabe Siria", En="Syrian Arab Republic" },
            new Country() { CountryName = "Taiwan, Province of China", Alpha2 = "TW", Alpha3 = "TWN", NumericCode = "158", Es="Taiwán", En="Taiwan, Province of China" },
            new Country() { CountryName = "Tajikistan", Alpha2 = "TJ", Alpha3 = "TJK", NumericCode = "762", Es="Tayikistán", En="Tajikistan" },
            new Country() { CountryName = "Tanzania, United Republic of", Alpha2 = "TZ", Alpha3 = "TZA", NumericCode = "834", Es="Tanzania", En="Tanzania, United Republic of" },
            new Country() { CountryName = "Thailand", Alpha2 = "TH", Alpha3 = "THA", NumericCode = "764", Es="Tailandia", En="Thailand" },
            new Country() { CountryName = "Timor-Leste", Alpha2 = "TL", Alpha3 = "TLS", NumericCode = "626", Es="Timor Oriental", En="Timor-Leste" },
            new Country() { CountryName = "Togo", Alpha2 = "TG", Alpha3 = "TGO", NumericCode = "768", Es="Togo", En="Togo" },
            new Country() { CountryName = "Tokelau", Alpha2 = "TK", Alpha3 = "TKL", NumericCode = "772", Es="Tokelau", En="Tokelau" },
            new Country() { CountryName = "Tonga", Alpha2 = "TO", Alpha3 = "TON", NumericCode = "776", Es="Tonga", En="Tonga" },
            new Country() { CountryName = "Trinidad and Tobago", Alpha2 = "TT", Alpha3 = "TTO", NumericCode = "780", Es="Trinidad y Tobago", En="Trinidad and Tobago" },
            new Country() { CountryName = "Tunisia", Alpha2 = "TN", Alpha3 = "TUN", NumericCode = "788", Es="Túnez", En="Tunisia" },
            new Country() { CountryName = "Turkey", Alpha2 = "TR", Alpha3 = "TUR", NumericCode = "792", Es="Turquía", En="Turkey" },
            new Country() { CountryName = "Turkmenistan", Alpha2 = "TM", Alpha3 = "TKM", NumericCode = "795", Es="Turkmenistán", En="Turkmenistan" },
            new Country() { CountryName = "Turks and Caicos Islands", Alpha2 = "TC", Alpha3 = "TCA", NumericCode = "796", Es="Islas Turcas y Caicos", En="Turks and Caicos Islands" },
            new Country() { CountryName = "Tuvalu", Alpha2 = "TV", Alpha3 = "TUV", NumericCode = "798", Es="Tuvalu", En="Tuvalu" },
            new Country() { CountryName = "Uganda", Alpha2 = "UG", Alpha3 = "UGA", NumericCode = "800", Es="Uganda", En="Uganda" },
            new Country() { CountryName = "Ukraine", Alpha2 = "UA", Alpha3 = "UKR", NumericCode = "804", Es="Ucrania", En="Ukraine" },
            new Country() { CountryName = "United Arab Emirates", Alpha2 = "AE", Alpha3 = "ARE", NumericCode = "784", Es="Emiratos Árabes Unidos", En="United Arab Emirates" },
            new Country() { CountryName = "United Kingdom of Great Britain and Northern Ireland", Alpha2 = "GB", Alpha3 = "GBR", NumericCode = "826", Es="Reino Unido", En="United Kingdom" },
            new Country() { CountryName = "United States of America", Alpha2 = "US", Alpha3 = "USA", NumericCode = "840", Es="Estados Unidos", En="United States of America" },
            new Country() { CountryName = "United States Minor Outlying Islands", Alpha2 = "UM", Alpha3 = "UMI", NumericCode = "581", Es="Islas Menores Alejadas de los Estados Unidos", En="United States Minor Outlying Islands" },
            new Country() { CountryName = "Uruguay", Alpha2 = "UY", Alpha3 = "URY", NumericCode = "858", Es="Uruguay", En="Uruguay" },
            new Country() { CountryName = "Uzbekistan", Alpha2 = "UZ", Alpha3 = "UZB", NumericCode = "860", Es="Uzbekistán", En="Uzbekistan" },
            new Country() { CountryName = "Vanuatu", Alpha2 = "VU", Alpha3 = "VUT", NumericCode = "548", Es="Vanuatu", En="Vanuatu" },
            new Country() { CountryName = "Venezuela, Bolivarian Republic of", Alpha2 = "VE", Alpha3 = "VEN", NumericCode = "862", Es="Venezuela", En="Venezuela, Bolivarian Republic of" },
            new Country() { CountryName = "Viet Nam", Alpha2 = "VN", Alpha3 = "VNM", NumericCode = "704", Es="Vietnam", En="Viet Nam" },
            new Country() { CountryName = "Virgin Islands (British)", Alpha2 = "VG", Alpha3 = "VGB", NumericCode = "092", Es="Islas Vírgenes Británicas", En="Virgin Islands (British)" },
            new Country() { CountryName = "Virgin Islands (U.S.)", Alpha2 = "VI", Alpha3 = "VIR", NumericCode = "850", Es="Islas Vírgenes de los Estados Unidos", En="Virgin Islands (U.S.)" },
            new Country() { CountryName = "Wallis and Futuna", Alpha2 = "WF", Alpha3 = "WLF", NumericCode = "876", Es="Wallis y Futuna", En="Wallis and Futuna" },
            new Country() { CountryName = "Western Sahara", Alpha2 = "EH", Alpha3 = "ESH", NumericCode = "732", Es="Sahara Occidental", En="Western Sahara" },
            new Country() { CountryName = "Yemen", Alpha2 = "YE", Alpha3 = "YEM", NumericCode = "887", Es="Yemen", En="Yemen" },
            new Country() { CountryName = "Zambia", Alpha2 = "ZM", Alpha3 = "ZMB", NumericCode = "894", Es="Zambia", En="Zambia" },
            new Country() { CountryName = "Zimbabwe", Alpha2 = "ZW", Alpha3 = "ZWE", NumericCode = "716", Es="Zimbabue", En="Zimbabwe" }
        };

        public static List<Language> Languages => new()
        {
            new Language() { LanguageName = "Abkhazian", IsoCode = "ab", En = "Abkhazian", Es = "Abjasio" },
            new Language() { LanguageName = "Afar", IsoCode = "aa", En = "Afar", Es = "Afar" },
            new Language() { LanguageName = "Afrikaans", IsoCode = "af", En = "Afrikaans", Es = "Afrikáans" },
            new Language() { LanguageName = "Albanian", IsoCode = "sq", En = "Albanian", Es = "Albanés" },
            new Language() { LanguageName = "Amharic", IsoCode = "am", En = "Amharic", Es = "Amárico" },
            new Language() { LanguageName = "Arabic", IsoCode = "ar", En = "Arabic", Es = "Árabe" },
            new Language() { LanguageName = "Armenian", IsoCode = "hy", En = "Armenian", Es = "Armenio" },
            new Language() { LanguageName = "Assamese", IsoCode = "as", En = "Assamese", Es = "Asamés" },
            new Language() { LanguageName = "Aymara", IsoCode = "ay", En = "Aymara", Es = "Aimara" },
            new Language() { LanguageName = "Azerbaijani", IsoCode = "az", En = "Azerbaijani", Es = "Azerbaiyano" },
            new Language() { LanguageName = "Bashkir", IsoCode = "ba", En = "Bashkir", Es = "Baskir" },
            new Language() { LanguageName = "Basque", IsoCode = "eu", En = "Basque", Es = "Vasco" },
            new Language() { LanguageName = "Bengali (Bangla)", IsoCode = "bn", En = "Bengali", Es = "Bengalí" },
            new Language() { LanguageName = "Bhutani", IsoCode = "dz", En = "Bhutani", Es = "Butanés" },
            new Language() { LanguageName = "Bihari", IsoCode = "bh", En = "Bihari", Es = "Bihari" },
            new Language() { LanguageName = "Bislama", IsoCode = "bi", En = "Bislama", Es = "Bislama" },
            new Language() { LanguageName = "Breton", IsoCode = "br", En = "Breton", Es = "Bretón" },
            new Language() { LanguageName = "Bulgarian", IsoCode = "bg", En = "Bulgarian", Es = "Búlgaro" },
            new Language() { LanguageName = "Burmese", IsoCode = "my", En = "Burmese", Es = "Birmano" },
            new Language() { LanguageName = "Byelorussian (Belarusian)", IsoCode = "be", En = "Belarusian", Es = "Bielorruso" },
            new Language() { LanguageName = "Cambodian", IsoCode = "km", En = "Cambodian", Es = "Camboyano" },
            new Language() { LanguageName = "Catalan", IsoCode = "ca", En = "Catalan", Es = "Catalán" },
            new Language() { LanguageName = "Chinese (Simplified)", IsoCode = "zh", En = "Chinese", Es = "Chino Simplificado" },
            new Language() { LanguageName = "Chinese (Traditional)", IsoCode = "zh", En = "Chinese", Es = "Chino Tradicional" },
            new Language() { LanguageName = "Corsican", IsoCode = "co", En = "Corsican", Es = "Corso" },
            new Language() { LanguageName = "Croatian", IsoCode = "hr", En = "Croatian", Es = "Croata" },
            new Language() { LanguageName = "Czech", IsoCode = "cs", En = "Czech", Es = "Checo" },
            new Language() { LanguageName = "Danish", IsoCode = "da", En = "Danish", Es = "Danés" },
            new Language() { LanguageName = "Dutch", IsoCode = "nl", En = "Dutch", Es = "Holandés" },
            new Language() { LanguageName = "English", IsoCode = "en", En = "English", Es = "Inglés" },
            new Language() { LanguageName = "Esperanto", IsoCode = "eo", En = "Esperanto", Es = "Esperanto" },
            new Language() { LanguageName = "Estonian", IsoCode = "et", En = "Estonian", Es = "Estonio" },
            new Language() { LanguageName = "Faeroese", IsoCode = "fo", En = "Faeroese", Es = "Feroés" },
            new Language() { LanguageName = "Farsi", IsoCode = "fa", En = "Farsi", Es = "Persa" },
            new Language() { LanguageName = "Fiji", IsoCode = "fj", En = "Fiji", Es = "Fiyiano" },
            new Language() { LanguageName = "Finnish", IsoCode = "fi", En = "Finnish", Es = "Finlandés" },
            new Language() { LanguageName = "French", IsoCode = "fr", En = "French", Es = "Francés" },
            new Language() { LanguageName = "Frisian", IsoCode = "fy", En = "Frisian", Es = "Frisón" },
            new Language() { LanguageName = "Galician", IsoCode = "gl", En = "Galician", Es = "Gallego" },
            new Language() { LanguageName = "Gaelic (Scottish)", IsoCode = "gd", En = "Gaelic", Es = "Gaélico Escocés" },
            new Language() { LanguageName = "Gaelic (Manx)", IsoCode = "gv", En = "Gaelic", Es = "Gaélico Manés" },
            new Language() { LanguageName = "Georgian", IsoCode = "ka", En = "Georgian", Es = "Georgiano" },
            new Language() { LanguageName = "German", IsoCode = "de", En = "German", Es = "Alemán" },
            new Language() { LanguageName = "Greek", IsoCode = "el", En = "Greek", Es = "Griego" },
            new Language() { LanguageName = "Greenlandic", IsoCode = "kl", En = "Greenlandic", Es = "Groenlandés" },
            new Language() { LanguageName = "Guarani", IsoCode = "gn", En = "Guarani", Es = "Guaraní" },
            new Language() { LanguageName = "Gujarati", IsoCode = "gu", En = "Gujarati", Es = "Guyaratí" },
            new Language() { LanguageName = "Hausa", IsoCode = "ha", En = "Hausa", Es = "Hausa" },
            new Language() { LanguageName = "Hebrew", IsoCode = "he", En = "Hebrew", Es = "Hebreo" },
            new Language() { LanguageName = "Hindi", IsoCode = "hi", En = "Hindi", Es = "Hindi" },
            new Language() { LanguageName = "Hungarian", IsoCode = "hu", En = "Hungarian", Es = "Húngaro" },
            new Language() { LanguageName = "Icelandic", IsoCode = "is", En = "Icelandic", Es = "Islandés" },
            new Language() { LanguageName = "Indonesian", IsoCode = "id", En = "Indonesian", Es = "Indonesio" },
            new Language() { LanguageName = "Interlingua", IsoCode = "ia", En = "Interlingua", Es = "Interlingua" },
            new Language() { LanguageName = "Interlingue", IsoCode = "ie", En = "Interlingue", Es = "Interlingue" },
            new Language() { LanguageName = "Inuktitut", IsoCode = "iu", En = "Inuktitut", Es = "Inuktitut" },
            new Language() { LanguageName = "Inupiak", IsoCode = "ik", En = "Inupiak", Es = "Iñupiaq" },
            new Language() { LanguageName = "Irish", IsoCode = "ga", En = "Irish", Es = "Irlandés" },
            new Language() { LanguageName = "Italian", IsoCode = "it", En = "Italian", Es = "Italiano" },
            new Language() { LanguageName = "Japanese", IsoCode = "ja", En = "Japanese", Es = "Japonés" },
            new Language() { LanguageName = "Javanese", IsoCode = "jv", En = "Javanese", Es = "Javanés" },
            new Language() { LanguageName = "Kannada", IsoCode = "kn", En = "Kannada", Es = "Canarés" },
            new Language() { LanguageName = "Kashmiri", IsoCode = "ks", En = "Kashmiri", Es = "Cachemiro" },
            new Language() { LanguageName = "Kazakh", IsoCode = "kk", En = "Kazakh", Es = "Kazajo" },
            new Language() { LanguageName = "Kinyarwanda (Ruanda)", IsoCode = "rw", En = "Kinyarwanda", Es = "Kinyarwanda" },
            new Language() { LanguageName = "Kirghiz", IsoCode = "ky", En = "Kirghiz", Es = "Kirguís" },
            new Language() { LanguageName = "Kirundi (Rundi)", IsoCode = "rn", En = "Kirundi", Es = "Kirundi" },
            new Language() { LanguageName = "Korean", IsoCode = "ko", En = "Korean", Es = "Coreano" },
            new Language() { LanguageName = "Kurdish", IsoCode = "ku", En = "Kurdish", Es = "Kurdo" },
            new Language() { LanguageName = "Laothian", IsoCode = "lo", En = "Laothian", Es = "Lao" },
            new Language() { LanguageName = "Latin", IsoCode = "la", En = "Latin", Es = "Latín" },
            new Language() { LanguageName = "Latvian (Lettish)", IsoCode = "lv", En = "Latvian", Es = "Letón" },
            new Language() { LanguageName = "Limburgish ( Limburger)", IsoCode = "li", En = "Limburgish", Es = "Limburgués" },
            new Language() { LanguageName = "Lingala", IsoCode = "ln", En = "Lingala", Es = "Lingala" },
            new Language() { LanguageName = "Lithuanian", IsoCode = "lt", En = "Lithuanian", Es = "Lituano" },
            new Language() { LanguageName = "Macedonian", IsoCode = "mk", En = "Macedonian", Es = "Macedonio" },
            new Language() { LanguageName = "Malagasy", IsoCode = "mg", En = "Malagasy", Es = "Malgache" },
            new Language() { LanguageName = "Malay", IsoCode = "ms", En = "Malay", Es = "Malayo" },
            new Language() { LanguageName = "Malayalam", IsoCode = "ml", En = "Malayalam", Es = "Malayalam" },
            new Language() { LanguageName = "Maltese", IsoCode = "mt", En = "Maltese", Es = "Maltés" },
            new Language() { LanguageName = "Maori", IsoCode = "mi", En = "Maori", Es = "Maorí" },
            new Language() { LanguageName = "Marathi", IsoCode = "mr", En = "Marathi", Es = "Maratí" },
            new Language() { LanguageName = "Moldavian", IsoCode = "mo", En = "Moldavian", Es = "Moldavo" },
            new Language() { LanguageName = "Mongolian", IsoCode = "mn", En = "Mongolian", Es = "Mongol" },
            new Language() { LanguageName = "Nauru", IsoCode = "na", En = "Nauru", Es = "Nauruano" },
            new Language() { LanguageName = "Nepali", IsoCode = "ne", En = "Nepali", Es = "Nepalí" },
            new Language() { LanguageName = "Norwegian", IsoCode = "no", En = "Norwegian", Es = "Noruego" },
            new Language() { LanguageName = "Occitan", IsoCode = "oc", En = "Occitan", Es = "Occitano" },
            new Language() { LanguageName = "Oriya", IsoCode = "or", En = "Oriya", Es = "Oriya" },
            new Language() { LanguageName = "Oromo (Afan, Galla)", IsoCode = "om", En = "Oromo", Es = "Oromo" },
            new Language() { LanguageName = "Pashto (Pushto)", IsoCode = "ps", En = "Pashto", Es = "Pastún" },
            new Language() { LanguageName = "Polish", IsoCode = "pl", En = "Polish", Es = "Polaco" },
            new Language() { LanguageName = "Portuguese", IsoCode = "pt", En = "Portuguese", Es = "Portugués" },
            new Language() { LanguageName = "Punjabi", IsoCode = "pa", En = "Punjabi", Es = "Panyabí" },
            new Language() { LanguageName = "Quechua", IsoCode = "qu", En = "Quechua", Es = "Quechua" },
            new Language() { LanguageName = "Rhaeto-Romance", IsoCode = "rm", En = "Rhaeto-Romance", Es = "Retorromano" },
            new Language() { LanguageName = "Romanian", IsoCode = "ro", En = "Romanian", Es = "Rumano" },
            new Language() { LanguageName = "Russian", IsoCode = "ru", En = "Russian", Es = "Ruso" },
            new Language() { LanguageName = "Samoan", IsoCode = "sm", En = "Samoan", Es = "Samoano" },
            new Language() { LanguageName = "Sangro", IsoCode = "sg", En = "Sango", Es = "Sango" },
            new Language() { LanguageName = "Sanskrit", IsoCode = "sa", En = "Sanskrit", Es = "Sánscrito" },
            new Language() { LanguageName = "Serbian", IsoCode = "sr", En = "Serbian", Es = "Serbio" },
            new Language() { LanguageName = "Serbo-Croatian", IsoCode = "sh", En = "Serbo-Croatian", Es = "Serbocroata" },
            new Language() { LanguageName = "Sesotho", IsoCode = "st", En = "Sesotho", Es = "Sesotho" },
            new Language() { LanguageName = "Setswana", IsoCode = "tn", En = "Setswana", Es = "Setsuana" },
            new Language() { LanguageName = "Shona", IsoCode = "sn", En = "Shona", Es = "Shona" },
            new Language() { LanguageName = "Sindhi", IsoCode = "sd", En = "Sindhi", Es = "Sindhi" },
            new Language() { LanguageName = "Sinhalese", IsoCode = "si", En = "Sinhalese", Es = "Cingalés" },
            new Language() { LanguageName = "Siswati", IsoCode = "ss", En = "Siswati", Es = "Siswati" },
            new Language() { LanguageName = "Slovak", IsoCode = "sk", En = "Slovak", Es = "Eslovaco" },
            new Language() { LanguageName = "Slovenian", IsoCode = "sl", En = "Slovenian", Es = "Esloveno" },
            new Language() { LanguageName = "Somali", IsoCode = "so", En = "Somali", Es = "Somalí" },
            new Language() { LanguageName = "Spanish", IsoCode = "es", En = "Spanish", Es = "Español" },
            new Language() { LanguageName = "Sundanese", IsoCode = "su", En = "Sundanese", Es = "Sundanés" },
            new Language() { LanguageName = "Swahili (Kiswahili)", IsoCode = "sw", En = "Swahili", Es = "Swahili" },
            new Language() { LanguageName = "Swedish", IsoCode = "sv", En = "Swedish", Es = "Sueco" },
            new Language() { LanguageName = "Tagalog", IsoCode = "tl", En = "Tagalog", Es = "Tagalo" },
            new Language() { LanguageName = "Tajik", IsoCode = "tg", En = "Tajik", Es = "Tayiko" },
            new Language() { LanguageName = "Tamil", IsoCode = "ta", En = "Tamil", Es = "Tamil" },
            new Language() { LanguageName = "Tatar", IsoCode = "tt", En = "Tatar", Es = "Tártaro" },
            new Language() { LanguageName = "Telugu", IsoCode = "te", En = "Telugu", Es = "Telugu" },
            new Language() { LanguageName = "Thai", IsoCode = "th", En = "Thai", Es = "Tailandés" },
            new Language() { LanguageName = "Tibetan", IsoCode = "bo", En = "Tibetan", Es = "Tibetano" },
            new Language() { LanguageName = "Tigrinya", IsoCode = "ti", En = "Tigrinya", Es = "Tigrinya" },
            new Language() { LanguageName = "Tonga", IsoCode = "to", En = "Tonga", Es = "Tongano" },
            new Language() { LanguageName = "Tsonga", IsoCode = "ts", En = "Tsonga", Es = "Tsonga" },
            new Language() { LanguageName = "Turkish", IsoCode = "tr", En = "Turkish", Es = "Turco" },
            new Language() { LanguageName = "Turkmen", IsoCode = "tk", En = "Turkmen", Es = "Turcomano" },
            new Language() { LanguageName = "Twi", IsoCode = "tw", En = "Twi", Es = "Twi" },
            new Language() { LanguageName = "Uighur", IsoCode = "ug", En = "Uighur", Es = "Uigur" },
            new Language() { LanguageName = "Ukrainian", IsoCode = "uk", En = "Ukrainian", Es = "Ucraniano" },
            new Language() { LanguageName = "Urdu", IsoCode = "ur", En = "Urdu", Es = "Urdu" },
            new Language() { LanguageName = "Uzbek", IsoCode = "uz", En = "Uzbek", Es = "Uzbeko" },
            new Language() { LanguageName = "Vietnamese", IsoCode = "vi", En = "Vietnamese", Es = "Vietnamita" },
            new Language() { LanguageName = "Volapük", IsoCode = "vo", En = "Volapük", Es = "Volapük" },
            new Language() { LanguageName = "Welsh", IsoCode = "cy", En = "Welsh", Es = "Galés" },
            new Language() { LanguageName = "Wolof", IsoCode = "wo", En = "Wolof", Es = "Wolof" },
            new Language() { LanguageName = "Xhosa", IsoCode = "xh", En = "Xhosa", Es = "Xhosa" },
            new Language() { LanguageName = "Yiddish", IsoCode = "yi", En = "Yiddish", Es = "Yídish" },
            new Language() { LanguageName = "Yoruba", IsoCode = "yo", En = "Yoruba", Es = "Yoruba" },
            new Language() { LanguageName = "Zulu", IsoCode = "zu", En = "Zulu", Es = "Zulú" }

        };

        public static List<Currency> Currencies => new()
        {
            new Currency() { CurrencyName = "Albania Lek", CurrencyCode = "ALL", Symbol = "Lek", En = "Albania Lek", Es = "Lek Albanés" },
            new Currency() { CurrencyName = "Afghanistan Afghani", CurrencyCode = "AFN", Symbol = "؋", En = "Afghanistan Afghani", Es = "Afgani Afgano" },
            new Currency() { CurrencyName = "Argentina Peso", CurrencyCode = "ARS", Symbol = "$", En = "Argentina Peso", Es = "Peso Argentino" },
            new Currency() { CurrencyName = "Aruba Guilder", CurrencyCode = "AWG", Symbol = "ƒ", En = "Aruba Guilder", Es = "Florín Arubeño" },
            new Currency() { CurrencyName = "Australia Dollar", CurrencyCode = "AUD", Symbol = "$", En = "Australia Dollar", Es = "Dólar Australiano" },
            new Currency() { CurrencyName = "Azerbaijan Manat", CurrencyCode = "AZN", Symbol = "₼", En = "Azerbaijan Manat", Es = "Manat Azerbaiyano" },
            new Currency() { CurrencyName = "Bahamas Dollar", CurrencyCode = "BSD", Symbol = "$", En = "Bahamas Dollar", Es = "Dólar Bahameño" },
            new Currency() { CurrencyName = "Barbados Dollar", CurrencyCode = "BBD", Symbol = "$", En = "Barbados Dollar", Es = "Dólar de Barbados" },
            new Currency() { CurrencyName = "Belarus Ruble", CurrencyCode = "BYN", Symbol = "Br", En = "Belarus Ruble", Es = "Rublo Bielorruso" },
            new Currency() { CurrencyName = "Belize Dollar", CurrencyCode = "BZD", Symbol = "BZ$", En = "Belize Dollar", Es = "Dólar Beliceño" },
            new Currency() { CurrencyName = "Bermuda Dollar", CurrencyCode = "BMD", Symbol = "$", En = "Bermuda Dollar", Es = "Dólar de Bermuda" },
            new Currency() { CurrencyName = "Bolivia Boliviano", CurrencyCode = "BOB", Symbol = "$b", En = "Bolivia Boliviano", Es = "Boliviano Boliviano" },
            new Currency() { CurrencyName = "Bosnia and Herzegovina Convertible Mark", CurrencyCode = "BAM", Symbol = "KM", En = "Bosnia and Herzegovina Convertible Mark", Es = "Marco Convertible de Bosnia y Herzegovina" },
            new Currency() { CurrencyName = "Botswana Pula", CurrencyCode = "BWP", Symbol = "P", En = "Botswana Pula", Es = "Pula de Botsuana" },
            new Currency() { CurrencyName = "Bulgaria Lev", CurrencyCode = "BGN", Symbol = "лв", En = "Bulgaria Lev", Es = "Lev Búlgaro" },
            new Currency() { CurrencyName = "Brazil Real", CurrencyCode = "BRL", Symbol = "R$", En = "Brazil Real", Es = "Real Brasileño" },
            new Currency() { CurrencyName = "Brunei Darussalam Dollar", CurrencyCode = "BND", Symbol = "$", En = "Brunei Darussalam Dollar", Es = "Dólar de Brunéi" },
            new Currency() { CurrencyName = "Cambodia Riel", CurrencyCode = "KHR", Symbol = "៛", En = "Cambodia Riel", Es = "Riel Camboyano" },
            new Currency() { CurrencyName = "Canada Dollar", CurrencyCode = "CAD", Symbol = "$", En = "Canada Dollar", Es = "Dólar Canadiense" },
            new Currency() { CurrencyName = "Cayman Islands Dollar", CurrencyCode = "KYD", Symbol = "$", En = "Cayman Islands Dollar", Es = "Dólar de las Islas Caimán" },
            new Currency() { CurrencyName = "Chile Peso", CurrencyCode = "CLP", Symbol = "$", En = "Chile Peso", Es = "Peso Chileno" },
            new Currency() { CurrencyName = "China Yuan Renminbi", CurrencyCode = "CNY", Symbol = "¥", En = "China Yuan Renminbi", Es = "Yuan Chino" },
            new Currency() { CurrencyName = "Colombia Peso", CurrencyCode = "COP", Symbol = "$", En = "Colombia Peso", Es = "Peso Colombiano" },
            new Currency() { CurrencyName = "Costa Rica Colon", CurrencyCode = "CRC", Symbol = "₡", En = "Costa Rica Colon", Es = "Colón Costarricense" },
            new Currency() { CurrencyName = "Croatia Kuna", CurrencyCode = "HRK", Symbol = "kn", En = "Croatia Kuna", Es = "Kuna Croata" },
            new Currency() { CurrencyName = "Cuba Peso", CurrencyCode = "CUP", Symbol = "₱", En = "Cuba Peso", Es = "Peso Cubano" },
            new Currency() { CurrencyName = "Czech Republic Koruna", CurrencyCode = "CZK", Symbol = "Kč", En = "Czech Republic Koruna", Es = "Corona Checa" },
            new Currency() { CurrencyName = "Denmark Krone", CurrencyCode = "DKK", Symbol = "kr", En = "Denmark Krone", Es = "Corona Danesa" },
            new Currency() { CurrencyName = "Dominican Republic Peso", CurrencyCode = "DOP", Symbol = "RD$", En = "Dominican Republic Peso", Es = "Peso Dominicano" },
            new Currency() { CurrencyName = "East Caribbean Dollar", CurrencyCode = "XCD", Symbol = "$", En = "East Caribbean Dollar", Es = "Dólar del Caribe Oriental" },
            new Currency() { CurrencyName = "Egypt Pound", CurrencyCode = "EGP", Symbol = "£", En = "Egypt Pound", Es = "Libra Egipcia" },
            new Currency() { CurrencyName = "El Salvador Colon", CurrencyCode = "SVC", Symbol = "$", En = "El Salvador Colon", Es = "Colón Salvadoreño" },
            new Currency() { CurrencyName = "Euro Member Countries", CurrencyCode = "EUR", Symbol = "€", En = "Euro Member Countries", Es = "Euro" },
            new Currency() { CurrencyName = "Falkland Islands (Malvinas) Pound", CurrencyCode = "FKP", Symbol = "£", En = "Falkland Islands (Malvinas) Pound", Es = "Libra de las Islas Malvinas" },
            new Currency() { CurrencyName = "Fiji Dollar", CurrencyCode = "FJD", Symbol = "$", En = "Fiji Dollar", Es = "Dólar Fiyiano" },
            new Currency() { CurrencyName = "Ghana Cedi", CurrencyCode = "GHS", Symbol = "¢", En = "Ghana Cedi", Es = "Cedi Ghanés" },
            new Currency() { CurrencyName = "Gibraltar Pound", CurrencyCode = "GIP", Symbol = "£", En = "Gibraltar Pound", Es = "Libra de Gibraltar" },
            new Currency() { CurrencyName = "Guatemala Quetzal", CurrencyCode = "GTQ", Symbol = "Q", En = "Guatemala Quetzal", Es = "Quetzal Guatemalteco" },
            new Currency() { CurrencyName = "Guernsey Pound", CurrencyCode = "GGP", Symbol = "£", En = "Guernsey Pound", Es = "Libra de Guernsey" },
            new Currency() { CurrencyName = "Guyana Dollar", CurrencyCode = "GYD", Symbol = "$", En = "Guyana Dollar", Es = "Dólar Guyanés" },
            new Currency() { CurrencyName = "Honduras Lempira", CurrencyCode = "HNL", Symbol = "L", En = "Honduras Lempira", Es = "Lempira Hondureño" },
            new Currency() { CurrencyName = "Hong Kong Dollar", CurrencyCode = "HKD", Symbol = "$", En = "Hong Kong Dollar", Es = "Dólar de Hong Kong" },
            new Currency() { CurrencyName = "Hungary Forint", CurrencyCode = "HUF", Symbol = "Ft", En = "Hungary Forint", Es = "Forinto Húngaro" },
            new Currency() { CurrencyName = "Iceland Krona", CurrencyCode = "ISK", Symbol = "kr", En = "Iceland Krona", Es = "Corona Islandesa" },
            new Currency() { CurrencyName = "India Rupee", CurrencyCode = "INR", Symbol = "₹", En = "India Rupee", Es = "Rupia India" },
            new Currency() { CurrencyName = "Indonesia Rupiah", CurrencyCode = "IDR", Symbol = "Rp", En = "Indonesia Rupiah", Es = "Rupia Indonesia" },
            new Currency() { CurrencyName = "Iran Rial", CurrencyCode = "IRR", Symbol = "﷼", En = "Iran Rial", Es = "Rial Iraní" },
            new Currency() { CurrencyName = "Isle of Man Pound", CurrencyCode = "IMP", Symbol = "£", En = "Isle of Man Pound", Es = "Libra de la Isla de Man" },
            new Currency() { CurrencyName = "Israel Shekel", CurrencyCode = "ILS", Symbol = "₪", En = "Israel Shekel", Es = "Shekel Israelí" },
            new Currency() { CurrencyName = "Jamaica Dollar", CurrencyCode = "JMD", Symbol = "J$", En = "Jamaica Dollar", Es = "Dólar Jamaiquino" },
            new Currency() { CurrencyName = "Japan Yen", CurrencyCode = "JPY", Symbol = "¥", En = "Japan Yen", Es = "Yen Japonés" },
            new Currency() { CurrencyName = "Jersey Pound", CurrencyCode = "JEP", Symbol = "£", En = "Jersey Pound", Es = "Libra de Jersey" },
            new Currency() { CurrencyName = "Kazakhstan Tenge", CurrencyCode = "KZT", Symbol = "лв", En = "Kazakhstan Tenge", Es = "Tenge Kazajo" },
            new Currency() { CurrencyName = "Korea (North) Won", CurrencyCode = "KPW", Symbol = "₩", En = "Korea (North) Won", Es = "Won Norcoreano" },
            new Currency() { CurrencyName = "Kyrgyzstan Som", CurrencyCode = "KGS", Symbol = "лв", En = "Kyrgyzstan Som", Es = "Som Kirguís" },
            new Currency() { CurrencyName = "Laos Kip", CurrencyCode = "LAK", Symbol = "₭", En = "Laos Kip", Es = "Kip Laosiano" },
            new Currency() { CurrencyName = "Lebanon Pound", CurrencyCode = "LBP", Symbol = "£", En = "Lebanon Pound", Es = "Libra Libanesa" },
            new Currency() { CurrencyName = "Liberia Dollar", CurrencyCode = "LRD", Symbol = "$", En = "Liberia Dollar", Es = "Dólar Liberiano" },
            new Currency() { CurrencyName = "Libya Dinar", CurrencyCode = "LYD", Symbol = "ل.د", En = "Libya Dinar", Es = "Dinar Libio" },
            new Currency() { CurrencyName = "Macau Pataca", CurrencyCode = "MOP", Symbol = "MOP$", En = "Macau Pataca", Es = "Pataca de Macao" },
            new Currency() { CurrencyName = "Macedonia Denar", CurrencyCode = "MKD", Symbol = "ден", En = "Macedonia Denar", Es = "Denar Macedonio" },
            new Currency() { CurrencyName = "Madagascar Ariary", CurrencyCode = "MGA", Symbol = "Ar", En = "Madagascar Ariary", Es = "Ariary Malgache" },
            new Currency() { CurrencyName = "Malawi Kwacha", CurrencyCode = "MWK", Symbol = "MK", En = "Malawi Kwacha", Es = "Kwacha Malauí" },
            new Currency() { CurrencyName = "Malaysia Ringgit", CurrencyCode = "MYR", Symbol = "RM", En = "Malaysia Ringgit", Es = "Ringgit Malayo" },
            new Currency() { CurrencyName = "Maldives Rufiyaa", CurrencyCode = "MVR", Symbol = "Rf", En = "Maldives Rufiyaa", Es = "Rufiyaa Maldiva" },
            new Currency() { CurrencyName = "Mauritania Ouguiya", CurrencyCode = "MRU", Symbol = "UM", En = "Mauritania Ouguiya", Es = "Uguiya Mauritana" },
            new Currency() { CurrencyName = "Mauritius Rupee", CurrencyCode = "MUR", Symbol = "₨", En = "Mauritius Rupee", Es = "Rupia de Mauricio" },
            new Currency() { CurrencyName = "Mexico Peso", CurrencyCode = "MXN", Symbol = "$", En = "Mexico Peso", Es = "Peso Mexicano" },
            new Currency() { CurrencyName = "Moldova Leu", CurrencyCode = "MDL", Symbol = "L", En = "Moldova Leu", Es = "Leu Moldavo" },
            new Currency() { CurrencyName = "Mongolia Tughrik", CurrencyCode = "MNT", Symbol = "₮", En = "Mongolia Tughrik", Es = "Tugrik Mongol" },
            new Currency() { CurrencyName = "Morocco Dirham", CurrencyCode = "MAD", Symbol = "MAD", En = "Morocco Dirham", Es = "Dirham Marroquí" },
            new Currency() { CurrencyName = "Mozambique Metical", CurrencyCode = "MZN", Symbol = "MT", En = "Mozambique Metical", Es = "Metical Mozambiqueño" },
            new Currency() { CurrencyName = "Myanmar (Burma) Kyat", CurrencyCode = "MMK", Symbol = "K", En = "Myanmar (Burma) Kyat", Es = "Kyat Birmano" },
            new Currency() { CurrencyName = "Namibia Dollar", CurrencyCode = "NAD", Symbol = "$", En = "Namibia Dollar", Es = "Dólar Namibio" },
            new Currency() { CurrencyName = "Nepal Rupee", CurrencyCode = "NPR", Symbol = "₨", En = "Nepal Rupee", Es = "Rupia Nepalí" },
            new Currency() { CurrencyName = "Netherlands Antilles Guilder", CurrencyCode = "ANG", Symbol = "ƒ", En = "Netherlands Antilles Guilder", Es = "Florín Antillano Neerlandés" },
            new Currency() { CurrencyName = "New Zealand Dollar", CurrencyCode = "NZD", Symbol = "$", En = "New Zealand Dollar", Es = "Dólar Neozelandés" },
            new Currency() { CurrencyName = "Nicaragua Cordoba", CurrencyCode = "NIO", Symbol = "C$", En = "Nicaragua Cordoba", Es = "Córdoba Nicaragüense" },
            new Currency() { CurrencyName = "Nigeria Naira", CurrencyCode = "NGN", Symbol = "₦", En = "Nigeria Naira", Es = "Naira Nigeriano" },
            new Currency() { CurrencyName = "Norway Krone", CurrencyCode = "NOK", Symbol = "kr", En = "Norway Krone", Es = "Corona Noruega" },
            new Currency() { CurrencyName = "Oman Rial", CurrencyCode = "OMR", Symbol = "﷼", En = "Oman Rial", Es = "Rial Omaní" },
            new Currency() { CurrencyName = "Pakistan Rupee", CurrencyCode = "PKR", Symbol = "₨", En = "Pakistan Rupee", Es = "Rupia Paquistaní" },
            new Currency() { CurrencyName = "Panama Balboa", CurrencyCode = "PAB", Symbol = "B/.", En = "Panama Balboa", Es = "Balboa Panameño" },
            new Currency() { CurrencyName = "Papua New Guinea Kina", CurrencyCode = "PGK", Symbol = "K", En = "Papua New Guinea Kina", Es = "Kina de Papúa Nueva Guinea" },
            new Currency() { CurrencyName = "Paraguay Guarani", CurrencyCode = "PYG", Symbol = "₲", En = "Paraguay Guarani", Es = "Guaraní Paraguayo" },
            new Currency() { CurrencyName = "Peru Sol", CurrencyCode = "PEN", Symbol = "S/.", En = "Peru Sol", Es = "Sol Peruano" },
            new Currency() { CurrencyName = "Philippines Peso", CurrencyCode = "PHP", Symbol = "₱", En = "Philippines Peso", Es = "Peso Filipino" },
            new Currency() { CurrencyName = "Poland Zloty", CurrencyCode = "PLN", Symbol = "zł", En = "Poland Zloty", Es = "Złoty Polaco" },
            new Currency() { CurrencyName = "Qatar Riyal", CurrencyCode = "QAR", Symbol = "﷼", En = "Qatar Riyal", Es = "Riyal Catarí" },
            new Currency() { CurrencyName = "Romania Leu", CurrencyCode = "RON", Symbol = "lei", En = "Romania Leu", Es = "Leu Rumano" },
            new Currency() { CurrencyName = "Russia Ruble", CurrencyCode = "RUB", Symbol = "₽", En = "Russia Ruble", Es = "Rublo Ruso" },
            new Currency() { CurrencyName = "Saint Helena Pound", CurrencyCode = "SHP", Symbol = "£", En = "Saint Helena Pound", Es = "Libra de Santa Helena" },
            new Currency() { CurrencyName = "Saudi Arabia Riyal", CurrencyCode = "SAR", Symbol = "﷼", En = "Saudi Arabia Riyal", Es = "Riyal Saudí" },
            new Currency() { CurrencyName = "Serbia Dinar", CurrencyCode = "RSD", Symbol = "Дин.", En = "Serbia Dinar", Es = "Dinar Serbio" },
            new Currency() { CurrencyName = "Seychelles Rupee", CurrencyCode = "SCR", Symbol = "₨", En = "Seychelles Rupee", Es = "Rupia de Seychelles" },
            new Currency() { CurrencyName = "Singapore Dollar", CurrencyCode = "SGD", Symbol = "$", En = "Singapore Dollar", Es = "Dólar de Singapur" },
            new Currency() { CurrencyName = "Solomon Islands Dollar", CurrencyCode = "SBD", Symbol = "$", En = "Solomon Islands Dollar", Es = "Dólar de las Islas Salomón" },
            new Currency() { CurrencyName = "Somalia Shilling", CurrencyCode = "SOS", Symbol = "S", En = "Somalia Shilling", Es = "Chelín Somalí" },
            new Currency() { CurrencyName = "South Africa Rand", CurrencyCode = "ZAR", Symbol = "R", En = "South Africa Rand", Es = "Rand Sudafricano" },
            new Currency() { CurrencyName = "Sri Lanka Rupee", CurrencyCode = "LKR", Symbol = "₨", En = "Sri Lanka Rupee", Es = "Rupia de Sri Lanka" },
            new Currency() { CurrencyName = "Sweden Krona", CurrencyCode = "SEK", Symbol = "kr", En = "Sweden Krona", Es = "Corona Sueca" },
            new Currency() { CurrencyName = "Switzerland Franc", CurrencyCode = "CHF", Symbol = "CHF", En = "Switzerland Franc", Es = "Franco Suizo" },
            new Currency() { CurrencyName = "Taiwan New Dollar", CurrencyCode = "TWD", Symbol = "NT$", En = "Taiwan New Dollar", Es = "Dólar Taiwánés" },
            new Currency() { CurrencyName = "Thailand Baht", CurrencyCode = "THB", Symbol = "฿", En = "Thailand Baht", Es = "Baht Tailandés" },
            new Currency() { CurrencyName = "Turkey Lira", CurrencyCode = "TRY", Symbol = "₺", En = "Turkey Lira", Es = "Lira Turca" },
            new Currency() { CurrencyName = "Ukraine Hryvnia", CurrencyCode = "UAH", Symbol = "₴", En = "Ukraine Hryvnia", Es = "Grivna Ucraniana" },
            new Currency() { CurrencyName = "United Kingdom Pound", CurrencyCode = "GBP", Symbol = "£", En = "United Kingdom Pound", Es = "Libra Esterlina" },
            new Currency() { CurrencyName = "United States Dollar", CurrencyCode = "USD", Symbol = "$", En = "United States Dollar", Es = "Dólar Estadounidense" },
            new Currency() { CurrencyName = "Uruguay Peso", CurrencyCode = "UYU", Symbol = "$U", En = "Uruguay Peso", Es = "Peso Uruguayo" },
            new Currency() { CurrencyName = "Uzbekistan Som", CurrencyCode = "UZS", Symbol = "лв", En = "Uzbekistan Som", Es = "Sum Uzbeko" },
            new Currency() { CurrencyName = "Venezuela Bolívar", CurrencyCode = "VES", Symbol = "Bs", En = "Venezuela Bolívar", Es = "Bolívar Venezolano" },
            new Currency() { CurrencyName = "Viet Nam Dong", CurrencyCode = "VND", Symbol = "₫", En = "Viet Nam Dong", Es = "Dong Vietnamita" },
            new Currency() { CurrencyName = "Yemen Rial", CurrencyCode = "YER", Symbol = "﷼", En = "Yemen Rial", Es = "Rial Yemení" },
            new Currency() { CurrencyName = "Zimbabwe Dollar", CurrencyCode = "ZWD", Symbol = "Z$", En = "Zimbabwe Dollar", Es = "Dólar Zimbabuense" }
        };
    };
}



